constraints:
  beach_slot_rule:
    allowed_slots:
    - 1
    - 3
    thursday_slot_2_allowed: true
  accuracy_limit:
    max_per_day: 1
    activities:
    - Troop Rifle
    - Troop Shotgun
    - Archery
  friday_reflection:
    required: true
    commissioner_clustering: true
  delta_before_super_troop: true
  max_accuracy_per_day: 1
optimization:
  area_clustering_priority:
  - Tower
  - Rifle Range
  - Archery
  - Outdoor Skills
  consecutive_activities:
  - Tie Dye
  - Archery
  avoid_friday:
  - Archery
  archery_target_days: 2
  enable_smart_balls_scheduling: true
  enable_area_day_filling: true
scheduling:
  default_fill_priority:
  - Super Troop
  - Aqua Trampoline
  - Climbing Tower
  - Archery
  - Water Polo
  - Troop Rifle
  - Gaga Ball
  - 9 Square
  - Troop Swim
  - Sailing
  - Trading Post
  - GPS & Geocaching
  - Disc Golf
  - Hemp Craft
  - Dr. DNA
  - Loon Lore
  - Fishing
  - Campsite Free Time
